[package]
name = "propagate"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
anyhow = "1.0.93"
trybuild = "1.0.101"

[features]
enum_index = []

[dependencies]
propagate-derive = {version = "0.1.0", path = "./proc_macros" }
