[package]
name = "sugar-try"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
anyhow = "1.0.93"

[dependencies]
anyhow = "1.0.93"
sugar-try-macros = {version = "0.1.0", path = "proc_macros" }

[[bin]]
path = "tests/main.rs"
name = "main"